package com.supplier.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderBillProcedures<M extends BaseOrderBillProcedures<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFId(java.lang.Integer fId) {
		set("fId", fId);
		return (M)this;
	}
	
	public java.lang.Integer getFId() {
		return getInt("fId");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setImgPath(java.lang.String imgPath) {
		set("imgPath", imgPath);
		return (M)this;
	}
	
	public java.lang.String getImgPath() {
		return getStr("imgPath");
	}

	public M setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
		return (M)this;
	}
	
	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public M setDeadline(java.util.Date deadline) {
		set("deadline", deadline);
		return (M)this;
	}
	
	public java.util.Date getDeadline() {
		return get("deadline");
	}

}
