package com.supplier.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderBill<M extends BaseOrderBill<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBillNo(java.lang.String billNo) {
		set("billNo", billNo);
		return (M)this;
	}
	
	public java.lang.String getBillNo() {
		return getStr("billNo");
	}

	public M setSupplierId(java.lang.String supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	public java.lang.String getSupplierId() {
		return getStr("supplierId");
	}

	public M setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
		return (M)this;
	}
	
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}

	public M setOrderDate(java.util.Date orderDate) {
		set("orderDate", orderDate);
		return (M)this;
	}
	
	public java.util.Date getOrderDate() {
		return get("orderDate");
	}

	public M setBuyerId(java.lang.String buyerId) {
		set("buyerId", buyerId);
		return (M)this;
	}
	
	public java.lang.String getBuyerId() {
		return getStr("buyerId");
	}

	public M setBuyerName(java.lang.String buyerName) {
		set("buyerName", buyerName);
		return (M)this;
	}
	
	public java.lang.String getBuyerName() {
		return getStr("buyerName");
	}

	public M setMerchandiserId(java.lang.String merchandiserId) {
		set("merchandiserId", merchandiserId);
		return (M)this;
	}
	
	public java.lang.String getMerchandiserId() {
		return getStr("merchandiserId");
	}

	public M setMerchandiserName(java.lang.String merchandiserName) {
		set("merchandiserName", merchandiserName);
		return (M)this;
	}
	
	public java.lang.String getMerchandiserName() {
		return getStr("merchandiserName");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setLastModified(java.util.Date lastModified) {
		set("lastModified", lastModified);
		return (M)this;
	}
	
	public java.util.Date getLastModified() {
		return get("lastModified");
	}

}
