package com.supplier.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYphGoods<M extends BaseYphGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setDes(java.lang.String des) {
		set("des", des);
		return (M)this;
	}
	
	public java.lang.String getDes() {
		return getStr("des");
	}

	public M setVerifyBy(java.lang.Integer verifyBy) {
		set("verifyBy", verifyBy);
		return (M)this;
	}
	
	public java.lang.Integer getVerifyBy() {
		return getInt("verifyBy");
	}

	public M setReplyMsg(java.lang.Integer replyMsg) {
		set("replyMsg", replyMsg);
		return (M)this;
	}
	
	public java.lang.Integer getReplyMsg() {
		return getInt("replyMsg");
	}

	public M setVerifyTime(java.util.Date verifyTime) {
		set("verifyTime", verifyTime);
		return (M)this;
	}
	
	public java.util.Date getVerifyTime() {
		return get("verifyTime");
	}

	public M setVerifyState(java.lang.Integer verifyState) {
		set("verifyState", verifyState);
		return (M)this;
	}
	
	public java.lang.Integer getVerifyState() {
		return getInt("verifyState");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("createBy", createBy);
		return (M)this;
	}
	
	public java.lang.Integer getCreateBy() {
		return getInt("createBy");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("updateBy", updateBy);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateBy() {
		return getInt("updateBy");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
