package com.supplier.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setCrearteDate(java.util.Date crearteDate) {
		set("crearteDate", crearteDate);
		return (M)this;
	}
	
	public java.util.Date getCrearteDate() {
		return get("crearteDate");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
		return (M)this;
	}

	/**
	 * 0：管理员，1:供应商，2：采购员
	 * @return
	 */
	public java.lang.Integer getRole() {
		return getInt("role");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	/**
	 * role为1时候supplierId为供应商编码（金蝶），role为0，1时候，supplierId为金蝶中的员工编号
	 * @param supplierId
	 * @return
	 */

	public M setSupplierId(java.lang.String supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	public java.lang.String getSupplierId() {
		return getStr("supplierId");
	}

}
