package com.supplier.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("orderBill", "id", OrderBill.class);
		arp.addMapping("orderBillProcedures", "id", OrderBillProcedures.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("yph_goods", "id", YphGoods.class);
		arp.addMapping("yph_goods_img", "id", YphGoodsImg.class);
	}
}

