package com.supplier.common.model;

import com.supplier.common.model.base.BaseOrderBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderBill extends BaseOrderBill<OrderBill> {
	
}
