package com.supplier.common.model;

import com.supplier.common.model.base.BaseOrderBillProcedures;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderBillProcedures extends BaseOrderBillProcedures<OrderBillProcedures> {
	
}
