package com.supplier.common.model;

import com.supplier.common.model.base.BaseYphGoods;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YphGoods extends BaseYphGoods<YphGoods> {

    public void setGoodsImgLis(List<YphGoodsImg> goodsImgLis) {
        put("goodsImgLis",goodsImgLis);
    }
}
