package com.supplier.common.model;

import com.supplier.common.model.base.BaseYphGoodsImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YphGoodsImg extends BaseYphGoodsImg<YphGoodsImg> {
	
}
